swagger: "2.0"
info:
  description: "This is a sample TestApp server."
  version: "1.0.0"
  title: "Swagger TestApp Documentation"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "khamitamantaev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "Data doc"
  description: "Everything about Data"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /data/push:
    post:
      tags:
      - "data"
      summary: "Add a new Data to the Database"
      description: ""
      operationId: "addData"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Data"
      responses:
        "200":
          shareCode: "code"
          adminCode: "code"
  /data/{shareCode}:
    get:
      tags:
      - "data"
      summary: "Find Data by shareCode"
      description: "Returns a single Data"
      operationId: "getPetById"
      produces:
      - "application/json"
      parameters:
      - name: "shareCode"
        in: "path"
        description: "shareCode of Data to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Data"
        "400":
          status: "400"
          message: "Bad request code"
      security:
      - api_key: []
  /data/update:
     put:
      tags:
      - "data"
      summary: "Update an existing Data"
      description: ""
      operationId: "updateData"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data object that needs to be update in Database"
        required: true
        schema:
          res: "asda"
          $ref: "#/definitions/Data"
      responses:
        "200":
          message: "Updated succesfully Data"
  /data/delete:
    delete:
      tags:
      - "data"
      summary: "Delete purchase Data by adminCode"
      description: "For valid response try enter valid adminCode value.  Negative or non-integer values will generate API errors"
      operationId: "deleteData"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data object that needs to be deleted in Database"
        required: true
        schema:
          $ref: "#/definitions/Code"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
  /clear:
    post:
      tags:
      - "clear data"
      summary: "Clear all data from DataBase"
      description: ""
      operationId: "clearData"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/UUID"
      responses:
        "200":
          shareCode: "code"
          adminCode: "code"

definitions:
  Data:
    type: "object"
    required:
    - "data"
    - "accessTimesCount"
    - "expirationTime"
    properties:
      data:
        type: "string"
        example: "data example"
      accessTimesCount:
        type: "string"
        example: "5"
      expirationTime:
        type: "string"
        format: "date"
        example: "2022-02-25T19:15:00.232Z"
  Code:
    type: "object"
    required:
    - "adminCode"
    properties:
      adminCode:
        type: "string"
        example: "EliMArNggtz8iEINuJn4RUnruxb4HuikA3vd+bfXJvE="
  UUID: 
    type: "object"
    required: 
    - "uuid"
    properties:
      code:
        type: "string"
        example: "9950eb01-6812-46a8-b7a6-372032c59feb"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"